/* ===== test_position_sensing.c ===== */
#include "unity.h"
#include "position_sensing.h"
#include "mock_stm32f4xx_hal.h"
// ADC handle is extern in production code
ADC_HandleTypeDef hadc1;
#define INVALID_POS_VALUE     ((uint8_t)0xA5)
void test_PS_01_Init_resets_internal_state(void){PositionSensing_Init();TEST_ASSERT_EQUAL_UINT8(0,PositionSensing_IsValid());uint8_t pos=INVALID_POS_VALUE;TEST_ASSERT_EQUAL_UINT8(0,PositionSensing_GetPosition(&pos));TEST_ASSERT_EQUAL_UINT8(INVALID_POS_VALUE,pos);}
void test_PS_02_GetPosition_rejects_NULL_pointer(void){PositionSensing_Init();TEST_ASSERT_EQUAL_UINT8(0,PositionSensing_GetPosition(NULL));}
void test_PS_03_Update_sets_valid_when_ADC_poll_OK_pos_0(void){PositionSensing_Init();HAL_ADC_Start_Expect(&hadc1);HAL_ADC_PollForConversion_ExpectAndReturn(&hadc1,2,HAL_OK);HAL_ADC_GetValue_ExpectAndReturn(&hadc1,4060);PositionSensing_Update();TEST_ASSERT_EQUAL_UINT8(1,PositionSensing_IsValid());uint8_t pos=INVALID_POS_VALUE;TEST_ASSERT_EQUAL_UINT8(1,PositionSensing_GetPosition(&pos));TEST_ASSERT_EQUAL_UINT8(0,pos);}
void test_PS_04_Map_ADC_to_position_1(void){PositionSensing_Init();HAL_ADC_Start_Expect(&hadc1);HAL_ADC_PollForConversion_ExpectAndReturn(&hadc1,2,HAL_OK);HAL_ADC_GetValue_ExpectAndReturn(&hadc1,3800);PositionSensing_Update();uint8_t pos=INVALID_POS_VALUE;TEST_ASSERT_EQUAL_UINT8(1,PositionSensing_GetPosition(&pos));TEST_ASSERT_EQUAL_UINT8(1,pos);}
void test_PS_05_Map_ADC_to_position_2(void){PositionSensing_Init();HAL_ADC_Start_Expect(&hadc1);HAL_ADC_PollForConversion_ExpectAndReturn(&hadc1,2,HAL_OK);HAL_ADC_GetValue_ExpectAndReturn(&hadc1,3500);PositionSensing_Update();uint8_t pos=INVALID_POS_VALUE;TEST_ASSERT_EQUAL_UINT8(1,PositionSensing_GetPosition(&pos));TEST_ASSERT_EQUAL_UINT8(2,pos);}
void test_PS_06_Map_ADC_to_position_3(void){PositionSensing_Init();HAL_ADC_Start_Expect(&hadc1);HAL_ADC_PollForConversion_ExpectAndReturn(&hadc1,2,HAL_OK);HAL_ADC_GetValue_ExpectAndReturn(&hadc1,3000);PositionSensing_Update();uint8_t pos=INVALID_POS_VALUE;TEST_ASSERT_EQUAL_UINT8(1,PositionSensing_GetPosition(&pos));TEST_ASSERT_EQUAL_UINT8(3,pos);}
void test_PS_07_Map_ADC_to_position_4(void){PositionSensing_Init();HAL_ADC_Start_Expect(&hadc1);HAL_ADC_PollForConversion_ExpectAndReturn(&hadc1,2,HAL_OK);HAL_ADC_GetValue_ExpectAndReturn(&hadc1,1500);PositionSensing_Update();uint8_t pos=INVALID_POS_VALUE;TEST_ASSERT_EQUAL_UINT8(1,PositionSensing_GetPosition(&pos));TEST_ASSERT_EQUAL_UINT8(4,pos);}
void test_PS_08_Map_ADC_to_position_5(void){PositionSensing_Init();HAL_ADC_Start_Expect(&hadc1);HAL_ADC_PollForConversion_ExpectAndReturn(&hadc1,2,HAL_OK);HAL_ADC_GetValue_ExpectAndReturn(&hadc1,500);PositionSensing_Update();uint8_t pos=INVALID_POS_VALUE;TEST_ASSERT_EQUAL_UINT8(1,PositionSensing_GetPosition(&pos));TEST_ASSERT_EQUAL_UINT8(5,pos);}
void test_PS_09_Update_sets_invalid_when_ADC_poll_error(void){PositionSensing_Init();HAL_ADC_Start_Expect(&hadc1);HAL_ADC_PollForConversion_ExpectAndReturn(&hadc1,2,HAL_ERROR);PositionSensing_Update();TEST_ASSERT_EQUAL_UINT8(0,PositionSensing_IsValid());uint8_t pos=INVALID_POS_VALUE;TEST_ASSERT_EQUAL_UINT8(0,PositionSensing_GetPosition(&pos));TEST_ASSERT_EQUAL_UINT8(INVALID_POS_VALUE,pos);}
void test_PS_10_GetPosition_returns_last_mapped_after_update(void){PositionSensing_Init();HAL_ADC_Start_Expect(&hadc1);HAL_ADC_PollForConversion_ExpectAndReturn(&hadc1,2,HAL_OK);HAL_ADC_GetValue_ExpectAndReturn(&hadc1,3000);PositionSensing_Update();uint8_t pos=0;TEST_ASSERT_EQUAL_UINT8(1,PositionSensing_GetPosition(&pos));TEST_ASSERT_EQUAL_UINT8(3,pos);}
void test_PS_11_IsAtTarget_rejects_out_of_range_target(void){PositionSensing_Init();TEST_ASSERT_EQUAL_UINT8(0,PositionSensing_IsAtTarget(6));TEST_ASSERT_EQUAL_UINT8(0,PositionSensing_IsAtTarget(10));TEST_ASSERT_EQUAL_UINT8(0,PositionSensing_IsAtTarget(0xFF));}
void test_PS_12_IsAtTarget_returns_1_when_adc_in_stop_range_0(void){PositionSensing_Init();HAL_ADC_Start_Expect(&hadc1);HAL_ADC_PollForConversion_ExpectAndReturn(&hadc1,2,HAL_OK);HAL_ADC_GetValue_ExpectAndReturn(&hadc1,4060);PositionSensing_Update();TEST_ASSERT_EQUAL_UINT8(1,PositionSensing_IsAtTarget(0));}
void test_PS_13_IsAtTarget_returns_0_when_adc_not_in_stop_range_0(void){PositionSensing_Init();HAL_ADC_Start_Expect(&hadc1);HAL_ADC_PollForConversion_ExpectAndReturn(&hadc1,2,HAL_OK);HAL_ADC_GetValue_ExpectAndReturn(&hadc1,4040);PositionSensing_Update();TEST_ASSERT_EQUAL_UINT8(0,PositionSensing_IsAtTarget(0));}
void test_PS_14_IsAtTarget_works_for_stop_3(void){PositionSensing_Init();HAL_ADC_Start_Expect(&hadc1);HAL_ADC_PollForConversion_ExpectAndReturn(&hadc1,2,HAL_OK);HAL_ADC_GetValue_ExpectAndReturn(&hadc1,3320);PositionSensing_Update();TEST_ASSERT_EQUAL_UINT8(1,PositionSensing_IsAtTarget(3));}